import { StyleSheet } from 'react-native';
import colors from '../../globals/colors';
import { FontSizes } from '../../globals/constants';
import { biDiTextAlign, rowDirection, marginStartEnd } from '../../globals/responsive';

export const itemsScreenStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.backgroundTertiary },
  container: { flex: 1, paddingHorizontal: 0, paddingTop: 4 },
  scrollContent: { paddingHorizontal: 16, paddingTop: 4, paddingBottom: 120, flexGrow: 1 },
  formContainer: { padding: 5, alignItems: 'center', borderRadius: 15, marginBottom: 15 },
  row: { flexDirection: rowDirection('row-reverse'), gap: 10, width: '100%', paddingHorizontal: 8 },
  field: { flex: 1 },
  fieldSmall: { flex: 0.5 },
  label: { fontSize: FontSizes.medium, fontWeight: '600', color: colors.textPrimary, marginBottom: 10, textAlign: 'center' },
  labelInline: { marginTop: 3, flex: 1, fontSize: FontSizes.medium, fontWeight: '600', color: colors.textPrimary, ...marginStartEnd(6, 0) },
  input: { backgroundColor: colors.white, borderRadius: 10, padding: 12, fontSize: FontSizes.body, textAlign: biDiTextAlign('right'), color: colors.textPrimary, borderWidth: 1, borderColor: colors.secondary },
  inputWrapper: { position: 'relative', justifyContent: 'center' },
  inputWithAdornment: { paddingRight: 30 },
  inputAdornment: { position: 'absolute', right: 10, color: colors.textSecondary, fontSize: FontSizes.body },
  counterRow: { flexDirection: rowDirection('row'), alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.white, borderRadius: 10, borderWidth: 1, borderColor: colors.secondary, paddingHorizontal: 8, paddingVertical: 6 },
  counterBtn: { backgroundColor: colors.pinkLight, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  counterText: { fontSize: FontSizes.medium, fontWeight: 'bold', color: colors.textPrimary },
  counterValue: { fontSize: FontSizes.medium, fontWeight: 'bold', color: colors.textPrimary, minWidth: 30, textAlign: 'center' },
  tagsRow: { marginTop: 10, alignItems: 'stretch', flexDirection: rowDirection('row-reverse'), flexWrap: 'wrap', gap: 3 },
  tag: { backgroundColor: colors.pinkLight, borderWidth: 1, borderColor: colors.secondary, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  tagSmall: { paddingHorizontal: 8, marginHorizontal: '4%', paddingVertical: 4 },
  tagSelected: { backgroundColor: colors.backgroundSecondary, borderColor: colors.success },
  tagText: { fontSize: FontSizes.small, color: colors.textPrimary },
  tagTextSm: { fontSize: FontSizes.caption },
  tagTextSelected: { color: colors.success, fontWeight: '600' },
  offerButton: { backgroundColor: colors.accent, padding: 14, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  offerButtonText: { color: colors.background, fontSize: FontSizes.medium, fontWeight: 'bold' },
  section: { marginBottom: 10 },
  sectionTitle: { fontSize: FontSizes.body, fontWeight: 'bold', alignSelf: 'center', color: colors.textPrimary, textAlign: 'center' },
  headerRow: { flexDirection: rowDirection('row-reverse'), justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, paddingHorizontal: 4 },
  clearButton: { backgroundColor: colors.pinkLight, borderWidth: 1, borderColor: colors.secondary, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 6 },
  clearButtonText: { fontSize: FontSizes.small, color: colors.textPrimary, fontWeight: '600' },
  noOuterScrollContainer: { flex: 1 },
  sectionWithScroller: { flex: 1, backgroundColor: colors.pinkLight, borderRadius: 12, borderWidth: 1, borderColor: colors.secondary, paddingVertical: 8, paddingHorizontal: 8 },
  innerScroll: { flex: 1 },
  itemsGridContainer: {},
  /** Matches search grid `COLUMN_GAP` in ItemsScreen — horizontal space between two cards per row. */
  columnWrapper: {
    gap: 8,
  },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 40 },
  emptyStateTitle: { fontSize: FontSizes.body, fontWeight: 'bold', color: colors.textPrimary, marginTop: 16, marginBottom: 8 },
  emptyStateText: { fontSize: FontSizes.small, color: colors.textSecondary, textAlign: 'center', marginBottom: 16 },
  emptyStateClearButton: { backgroundColor: colors.accent, paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8, marginTop: 8 },
  emptyStateClearButtonText: { fontSize: FontSizes.small, color: colors.background, fontWeight: '600' },
  itemCardWrapper: { marginBottom: 8, width: '100%' },
  itemCard: { backgroundColor: colors.pinkLight, borderRadius: 10, padding: 8, borderWidth: 1, borderColor: colors.secondary },
  itemRow: { flexDirection: rowDirection('row-reverse'), justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  itemTitle: { fontSize: FontSizes.small, fontWeight: 'bold', color: colors.textPrimary, textAlign: biDiTextAlign('right'), flex: 1, marginLeft: 6 },
  itemMeta: { fontSize: FontSizes.small, color: colors.textSecondary },
  itemBadge: { backgroundColor: colors.backgroundSecondary, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, marginLeft: 6 },
  itemBadgeText: { fontSize: FontSizes.small, color: colors.success, fontWeight: 'bold' },
  recentContainer: { paddingHorizontal: 8, paddingVertical: 8 },
  recentItemWrapper: { marginBottom: 8, width: '100%' },
  restoreChip: { backgroundColor: colors.pinkLight, borderWidth: 1, borderColor: colors.secondary, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  restoreChipText: { fontSize: FontSizes.small, color: colors.textPrimary, fontWeight: '600' },
  deleteButton: {
    padding: 6,
    marginLeft: 12,
    backgroundColor: colors.pinkLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.pinkLight,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 32,
    minHeight: 32,
  },
  itemImageContainer: {
    padding: 4,
    marginBottom: 4,
  },
  itemImageIndicator: {
    fontSize: FontSizes.small,
    color: colors.primary,
    fontWeight: '600',
  },
  imageSection: {
    width: '100%',
    marginTop: 8,
    marginBottom: 8,
  },
  imagePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 12,
    padding: 16,
    gap: 8,
    marginTop: 4,
  },
  imagePickerText: {
    color: colors.primary,
    fontSize: FontSizes.medium,
    fontWeight: '600',
  },
  imagePreview: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  previewImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  removeImageButton: {
    marginLeft: 'auto',
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 20,
    padding: 4,
  },
  imageInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
  },
  imageInfoText: {
    fontSize: FontSizes.medium,
    color: colors.success,
    fontWeight: '600',
  },
  imageInfoSubtext: {
    fontSize: FontSizes.small,
    color: colors.textSecondary,
    marginTop: 2,
  },
  dropdownButton: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.secondary,
    flexDirection: rowDirection('row-reverse'),
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 48,
  },
  dropdownButtonText: {
    fontSize: FontSizes.body,
    color: colors.textPrimary,
    textAlign: biDiTextAlign('right'),
    flex: 1,
  },
  dropdownPlaceholder: {
    color: colors.textSecondary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 16,
    width: '85%',
    maxHeight: '70%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: rowDirection('row-reverse'),
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontSize: FontSizes.heading2,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  modalCloseButton: {
    padding: 4,
  },
  dropdownList: {
    maxHeight: 400,
  },
  dropdownItem: {
    flexDirection: rowDirection('row-reverse'),
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dropdownItemSelected: {
    backgroundColor: colors.pinkLight,
  },
  dropdownItemIcon: {
    marginLeft: 12,
  },
  dropdownItemText: {
    fontSize: FontSizes.body,
    color: colors.textPrimary,
    flex: 1,
    textAlign: biDiTextAlign('right'),
  },
  dropdownItemTextSelected: {
    color: colors.primary,
    fontWeight: '600',
  },
  gridContainer: {
    flexDirection: rowDirection('row-reverse'),
    flexWrap: 'wrap',
    width: '100%',
  },
  gridItemWrapper: {
    marginBottom: 8,
  },
  openRequestsToggle: {
    flexDirection: rowDirection('row-reverse'),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 8,
    paddingHorizontal: 4,
    gap: 8,
    width: '100%',
  },
});
