/**
 * @file Landing styles
 * @description Shared StyleSheet for Landing page components
 * @module Landing/Styles
 */

import { StyleSheet } from 'react-native';
import colors from '../../../globals/colors';
import { IS_WEB, IS_MOBILE_WEB, IS_TABLET, SCREEN_WIDTH } from '../constants';

const styles = StyleSheet.create({
  // Section
  section: {
    paddingHorizontal: IS_MOBILE_WEB ? 16 : (IS_WEB ? (IS_TABLET ? 40 : 24) : 40),
    paddingVertical: IS_MOBILE_WEB ? 24 : (IS_WEB ? (IS_TABLET ? 60 : 40) : 50),
    width: '100%',
    alignSelf: 'center',
    maxWidth: IS_TABLET ? 1200 : '100%',
  },
  sectionTitle: {
    fontSize: IS_MOBILE_WEB ? 20 : (IS_WEB ? (IS_TABLET ? 36 : 28) : 42),
    fontWeight: '900',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 6 : 8,
    letterSpacing: -0.5,
  },
  titleDecorator: {
    width: IS_MOBILE_WEB ? 40 : 60,
    height: IS_MOBILE_WEB ? 3 : 4,
    backgroundColor: colors.info,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: IS_MOBILE_WEB ? 16 : 24,
  },
  sectionSubtitle: {
    fontSize: IS_MOBILE_WEB ? 13 : (IS_WEB ? (IS_TABLET ? 18 : 16) : 22),
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 12 : (IS_WEB ? 20 : 24),
    lineHeight: IS_MOBILE_WEB ? 18 : (IS_WEB ? 26 : 30),
    fontWeight: '500',
  },

  // Feature
  feature: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 280,
    maxWidth: IS_MOBILE_WEB ? '100%' : 350,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    padding: IS_MOBILE_WEB ? 16 : 28,
    alignItems: 'center',
    margin: IS_MOBILE_WEB ? 4 : 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
  },
  featureEmoji: {
    fontSize: IS_MOBILE_WEB ? 32 : 48,
    marginBottom: IS_MOBILE_WEB ? 10 : 16,
  },
  featureTitle: {
    fontSize: IS_MOBILE_WEB ? 16 : 24,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
    letterSpacing: -0.3,
  },
  featureText: {
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: IS_MOBILE_WEB ? 18 : 28,
    fontWeight: '400',
  },

  // Floating menu
  menuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    zIndex: 999,
  },
  floatingMenu: {
    position: 'absolute',
    right: IS_MOBILE_WEB ? 8 : 20,
    top: IS_MOBILE_WEB ? 60 : 100,
    minWidth: 150,
    width: IS_MOBILE_WEB ? '14%' : '10%',
    maxHeight: (IS_MOBILE_WEB ? '70vh' : (IS_WEB ? '80vh' : 600)) as any,
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 1000,
    overflow: 'hidden',
  },
  floatingMenuMinimized: {
    position: 'absolute',
    right: IS_MOBILE_WEB ? 8 : 20,
    top: IS_MOBILE_WEB ? 60 : 100,
    width: IS_MOBILE_WEB ? SCREEN_WIDTH * 0.05 : SCREEN_WIDTH * 0.03,
    height: IS_MOBILE_WEB ? SCREEN_WIDTH * 0.05 : SCREEN_WIDTH * 0.03,
    borderRadius: IS_MOBILE_WEB ? SCREEN_WIDTH * 0.025 : SCREEN_WIDTH * 0.015,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    zIndex: 1000,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuToggleButton: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SCREEN_WIDTH * 0.01,
    paddingVertical: SCREEN_WIDTH * 0.008,
    borderBottomWidth: 1,
    borderBottomColor: colors.backgroundSecondary,
    backgroundColor: colors.backgroundSecondary,
  },
  menuTitle: {
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: -0.3,
  },
  menuItems: {
    flex: 1,
    paddingVertical: SCREEN_WIDTH * 0.006,
  },
  menuItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: SCREEN_WIDTH * 0.006,
    borderRightWidth: 3,
    borderRightColor: 'transparent',
  },
  menuItemActive: {
    backgroundColor: colors.backgroundTertiary,
    borderRightColor: colors.info,
  },
  menuItemIcon: {
    marginLeft: SCREEN_WIDTH * 0.002,
  },
  menuItemText: {
    fontWeight: '600',
    color: colors.textSecondary,
    flex: 1,
    textAlign: 'right',
  },
  menuItemTextActive: {
    color: colors.info,
    fontWeight: '700',
  },

  // Hero
  hero: {
    width: '100%',
    overflow: 'hidden',
  },
  heroGradient: {
    backgroundColor: colors.backgroundTertiary,
    paddingTop: IS_MOBILE_WEB ? 40 : (IS_WEB ? 60 : 80),
    paddingBottom: IS_MOBILE_WEB ? 30 : (IS_WEB ? 50 : 70),
    paddingHorizontal: IS_MOBILE_WEB ? 16 : (IS_WEB ? 20 : 40),
    position: 'relative',
  },
  heroContent: {
    alignItems: 'center',
    zIndex: 2,
  },
  welcomeTitle: {
    fontSize: IS_MOBILE_WEB ? 28 : (IS_WEB ? (IS_TABLET ? 56 : 42) : 64),
    fontWeight: '900',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 16 : (IS_WEB ? 24 : 32),
    letterSpacing: -1,
    lineHeight: IS_MOBILE_WEB ? 34 : (IS_WEB ? (IS_TABLET ? 64 : 50) : 72),
  },
  welcomeTitleLarge: {
    fontSize: IS_MOBILE_WEB ? 32 : (IS_WEB ? (IS_TABLET ? 64 : 48) : 72),
    fontWeight: '900',
    color: colors.textPrimary,
  },
  welcomeTitleSmall: {
    fontSize: IS_MOBILE_WEB ? 24 : (IS_WEB ? (IS_TABLET ? 48 : 36) : 56),
    fontWeight: '900',
    color: colors.textPrimary,
  },
  logoContainer: {
    position: 'relative',
    marginBottom: IS_MOBILE_WEB ? 12 : (IS_WEB ? 20 : 28),
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: IS_MOBILE_WEB ? 140 : (IS_WEB ? (IS_TABLET ? 240 : 220) : 260),
    overflow: 'hidden',
  },
  logoBackground: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: IS_MOBILE_WEB ? 180 : (IS_WEB ? (IS_TABLET ? 320 : 280) : 360),
    height: IS_MOBILE_WEB ? 180 : (IS_WEB ? (IS_TABLET ? 320 : 280) : 360),
    opacity: 0.35,
  },
  title: {
    fontSize: IS_MOBILE_WEB ? 24 : (IS_WEB ? (IS_TABLET ? 48 : 36) : 56),
    fontWeight: '900',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 12 : (IS_WEB ? 16 : 20),
    letterSpacing: -0.5,
  },
  subtitlesRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 12 : (IS_WEB ? (IS_TABLET ? 28 : 20) : 32),
    marginBottom: IS_MOBILE_WEB ? 8 : (IS_WEB ? 12 : 16),
    flexWrap: 'wrap',
  },
  subtitleItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 6 : (IS_WEB ? (IS_TABLET ? 12 : 10) : 14),
    paddingHorizontal: IS_MOBILE_WEB ? 8 : (IS_WEB ? (IS_TABLET ? 16 : 12) : 20),
    paddingVertical: IS_MOBILE_WEB ? 6 : (IS_WEB ? (IS_TABLET ? 10 : 8) : 12),
    borderRadius: IS_MOBILE_WEB ? 12 : (IS_WEB ? (IS_TABLET ? 20 : 16) : 24),
    backgroundColor: colors.backgroundTertiary,
    borderWidth: 1,
    borderColor: colors.info + '30',
  },
  subtitleItemGreen: {
    backgroundColor: colors.greenBright + '18',
    borderColor: colors.greenBright + '50',
  },
  subtitleIcon: {
    marginTop: IS_MOBILE_WEB ? 1 : 2,
  },
  subtitleText: {
    fontSize: IS_MOBILE_WEB ? 12 : (IS_WEB ? (IS_TABLET ? 24 : 18) : 28),
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: IS_MOBILE_WEB ? 14 : (IS_WEB ? (IS_TABLET ? 20 : 18) : 24),
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: IS_MOBILE_WEB ? 6 : (IS_WEB ? 8 : 12),
    maxWidth: IS_MOBILE_WEB ? '95%' : (IS_TABLET ? '70%' : '90%'),
    lineHeight: IS_MOBILE_WEB ? 20 : (IS_WEB ? 28 : 32),
    fontWeight: '500',
  },
  ctaRow: {
    flexDirection: 'row',
    gap: IS_MOBILE_WEB ? 10 : 16,
    marginTop: IS_MOBILE_WEB ? 24 : 40,
    justifyContent: 'center',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  contactButton: {
    flexDirection: 'row',
    gap: IS_MOBILE_WEB ? 8 : 12,
    alignItems: 'center',
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 28,
    paddingVertical: IS_MOBILE_WEB ? 12 : 18,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    minWidth: IS_MOBILE_WEB ? 140 : 200,
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
  },
  contactButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    letterSpacing: 0.3,
  },
  donationCtaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
    backgroundColor: colors.secondary,
    paddingVertical: IS_MOBILE_WEB ? 14 : 18,
    paddingHorizontal: IS_MOBILE_WEB ? 24 : 32,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    marginTop: IS_MOBILE_WEB ? 20 : 28,
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  donationCtaButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    letterSpacing: 0.3,
  },
});

export { styles };
