/**
 * @file Landing styles
 * @description Shared StyleSheet for Landing page components
 * @module Landing/Styles
 */

import { StyleSheet } from 'react-native';
import colors from '../../../globals/colors';
import { IS_WEB, IS_MOBILE_WEB, IS_TABLET, SCREEN_WIDTH } from '../constants';

const styles = StyleSheet.create({
  // Section
  section: {
    paddingHorizontal: IS_MOBILE_WEB ? 16 : (IS_WEB ? (IS_TABLET ? 40 : 24) : 40),
    paddingVertical: IS_MOBILE_WEB ? 24 : (IS_WEB ? (IS_TABLET ? 60 : 40) : 50),
    width: '100%',
    alignSelf: 'center',
    maxWidth: IS_TABLET ? 1200 : '100%',
  },
  sectionTitle: {
    fontSize: IS_MOBILE_WEB ? 20 : (IS_WEB ? (IS_TABLET ? 36 : 28) : 42),
    fontWeight: '900',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 6 : 8,
    letterSpacing: -0.5,
  },
  titleDecorator: {
    width: IS_MOBILE_WEB ? 40 : 60,
    height: IS_MOBILE_WEB ? 3 : 4,
    backgroundColor: colors.info,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: IS_MOBILE_WEB ? 16 : 24,
  },
  sectionSubtitle: {
    fontSize: IS_MOBILE_WEB ? 13 : (IS_WEB ? (IS_TABLET ? 18 : 16) : 22),
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 12 : (IS_WEB ? 20 : 24),
    lineHeight: IS_MOBILE_WEB ? 18 : (IS_WEB ? 26 : 30),
    fontWeight: '500',
  },
  sectionAltBackground: {
    backgroundColor: colors.backgroundSecondary,
  },
  sectionSubTitle: {
    fontSize: IS_MOBILE_WEB ? 14 : (IS_WEB ? 18 : 24),
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
    marginTop: IS_MOBILE_WEB ? 10 : (IS_WEB ? 15 : 20),
    marginBottom: IS_MOBILE_WEB ? 6 : (IS_WEB ? 8 : 12),
  },
  paragraph: {
    fontSize: IS_MOBILE_WEB ? 14 : (IS_WEB ? 18 : 20),
    color: colors.textPrimary,
    lineHeight: IS_MOBILE_WEB ? 20 : (IS_WEB ? 28 : 30),
    textAlign: 'center',
    marginTop: IS_MOBILE_WEB ? 8 : 12,
    maxWidth: IS_MOBILE_WEB ? '95%' : (IS_TABLET ? '80%' : '90%'),
    alignSelf: 'center',
    fontWeight: '400',
  },
  emphasis: {
    fontWeight: '800',
    color: colors.info,
  },
  mottoContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 16 : 24,
    marginTop: IS_MOBILE_WEB ? 20 : 32,
    marginBottom: IS_MOBILE_WEB ? 20 : 32,
    width: '100%',
  },
  mottoCard: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 280,
    maxWidth: IS_MOBILE_WEB ? '100%' : 400,
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 20 : 32,
    borderWidth: 2,
    borderColor: colors.info,
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 12 : 16,
    shadowColor: colors.info,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 6,
  },
  mottoIcon: {
    marginBottom: IS_MOBILE_WEB ? 4 : 8,
  },
  mottoText: {
    fontSize: IS_MOBILE_WEB ? 16 : 22,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: IS_MOBILE_WEB ? 22 : 30,
  },
  visionHighlights: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 16 : 24,
    marginTop: IS_MOBILE_WEB ? 20 : 32,
    width: '100%',
  },
  visionHighlight: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 200,
    maxWidth: IS_MOBILE_WEB ? '100%' : 250,
    alignItems: 'center',
    padding: IS_MOBILE_WEB ? 16 : 24,
    gap: IS_MOBILE_WEB ? 8 : 12,
  },
  visionHighlightText: {
    fontSize: IS_MOBILE_WEB ? 13 : 16,
    color: colors.textPrimary,
    textAlign: 'center',
    fontWeight: '600',
  },

  // Feature
  feature: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 280,
    maxWidth: IS_MOBILE_WEB ? '100%' : 350,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    padding: IS_MOBILE_WEB ? 16 : 28,
    alignItems: 'center',
    margin: IS_MOBILE_WEB ? 4 : 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
  },
  featureEmoji: {
    fontSize: IS_MOBILE_WEB ? 32 : 48,
    marginBottom: IS_MOBILE_WEB ? 10 : 16,
  },
  featureTitle: {
    fontSize: IS_MOBILE_WEB ? 16 : 24,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
    letterSpacing: -0.3,
  },
  featureText: {
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: IS_MOBILE_WEB ? 18 : 28,
    fontWeight: '400',
  },

  // Floating menu
  menuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.overlayLight,
    zIndex: 999,
  },
  floatingMenu: {
    position: 'absolute',
    right: IS_MOBILE_WEB ? 8 : 20,
    top: IS_MOBILE_WEB ? 60 : 100,
    minWidth: 150,
    width: IS_MOBILE_WEB ? '14%' : '10%',
    maxHeight: (IS_MOBILE_WEB ? '70vh' : (IS_WEB ? '80vh' : 600)) as never,
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 1000,
    overflow: 'hidden',
  },
  floatingMenuMinimized: {
    position: 'absolute',
    right: IS_MOBILE_WEB ? 8 : 20,
    top: IS_MOBILE_WEB ? 60 : 100,
    width: IS_MOBILE_WEB ? SCREEN_WIDTH * 0.05 : SCREEN_WIDTH * 0.03,
    height: IS_MOBILE_WEB ? SCREEN_WIDTH * 0.05 : SCREEN_WIDTH * 0.03,
    borderRadius: IS_MOBILE_WEB ? SCREEN_WIDTH * 0.025 : SCREEN_WIDTH * 0.015,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    zIndex: 1000,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuToggleButton: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SCREEN_WIDTH * 0.01,
    paddingVertical: SCREEN_WIDTH * 0.008,
    borderBottomWidth: 1,
    borderBottomColor: colors.backgroundSecondary,
    backgroundColor: colors.backgroundSecondary,
  },
  menuTitle: {
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: -0.3,
  },
  menuItems: {
    flex: 1,
    paddingVertical: SCREEN_WIDTH * 0.006,
  },
  menuItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: SCREEN_WIDTH * 0.006,
    borderRightWidth: 3,
    borderRightColor: 'transparent',
  },
  menuItemActive: {
    backgroundColor: colors.backgroundTertiary,
    borderRightColor: colors.info,
  },
  menuItemIcon: {
    marginLeft: SCREEN_WIDTH * 0.002,
  },
  menuItemText: {
    fontWeight: '600',
    color: colors.textSecondary,
    flex: 1,
    textAlign: 'right',
  },
  menuItemTextActive: {
    color: colors.info,
    fontWeight: '700',
  },

  // Hero
  hero: {
    width: '100%',
    overflow: 'hidden',
  },
  heroGradient: {
    backgroundColor: colors.backgroundTertiary,
    paddingTop: IS_MOBILE_WEB ? 40 : (IS_WEB ? 60 : 80),
    paddingBottom: IS_MOBILE_WEB ? 30 : (IS_WEB ? 50 : 70),
    paddingHorizontal: IS_MOBILE_WEB ? 16 : (IS_WEB ? 20 : 40),
    position: 'relative',
  },
  decoCircle1: {
    position: 'absolute',
    width: IS_MOBILE_WEB ? 200 : 400,
    height: IS_MOBILE_WEB ? 200 : 400,
    borderRadius: IS_MOBILE_WEB ? 100 : 200,
    backgroundColor: colors.infoTintBackground,
    top: IS_MOBILE_WEB ? -50 : -100,
    left: IS_MOBILE_WEB ? -75 : -150,
  },
  decoCircle2: {
    position: 'absolute',
    width: IS_MOBILE_WEB ? 150 : 300,
    height: IS_MOBILE_WEB ? 150 : 300,
    borderRadius: IS_MOBILE_WEB ? 75 : 150,
    backgroundColor: colors.donateCtaBg,
    bottom: IS_MOBILE_WEB ? -25 : -50,
    right: IS_MOBILE_WEB ? -50 : -100,
  },
  decoCircle3: {
    position: 'absolute',
    width: IS_MOBILE_WEB ? 120 : 240,
    height: IS_MOBILE_WEB ? 120 : 240,
    borderRadius: IS_MOBILE_WEB ? 60 : 120,
    backgroundColor: colors.greenBright + '20',
    top: IS_MOBILE_WEB ? 40 : 80,
    right: IS_MOBILE_WEB ? -30 : -60,
  },
  heroContent: {
    alignItems: 'center',
    zIndex: 2,
  },
  welcomeTitle: {
    fontSize: IS_MOBILE_WEB ? 28 : (IS_WEB ? (IS_TABLET ? 56 : 42) : 64),
    fontWeight: '900',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 16 : (IS_WEB ? 24 : 32),
    letterSpacing: -1,
    lineHeight: IS_MOBILE_WEB ? 34 : (IS_WEB ? (IS_TABLET ? 64 : 50) : 72),
  },
  welcomeTitleLarge: {
    fontSize: IS_MOBILE_WEB ? 32 : (IS_WEB ? (IS_TABLET ? 64 : 48) : 72),
    fontWeight: '900',
    color: colors.textPrimary,
  },
  welcomeTitleSmall: {
    fontSize: IS_MOBILE_WEB ? 24 : (IS_WEB ? (IS_TABLET ? 48 : 36) : 56),
    fontWeight: '900',
    color: colors.textPrimary,
  },
  logoContainer: {
    position: 'relative',
    marginBottom: IS_MOBILE_WEB ? 12 : (IS_WEB ? 20 : 28),
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: IS_MOBILE_WEB ? 140 : (IS_WEB ? (IS_TABLET ? 240 : 220) : 260),
    overflow: 'hidden',
  },
  logoBackground: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    width: IS_MOBILE_WEB ? 180 : (IS_WEB ? (IS_TABLET ? 320 : 280) : 360),
    height: IS_MOBILE_WEB ? 180 : (IS_WEB ? (IS_TABLET ? 320 : 280) : 360),
    opacity: 0.35,
  },
  title: {
    fontSize: IS_MOBILE_WEB ? 24 : (IS_WEB ? (IS_TABLET ? 48 : 36) : 56),
    fontWeight: '900',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 12 : (IS_WEB ? 16 : 20),
    letterSpacing: -0.5,
  },
  subtitlesRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 12 : (IS_WEB ? (IS_TABLET ? 28 : 20) : 32),
    marginBottom: IS_MOBILE_WEB ? 8 : (IS_WEB ? 12 : 16),
    flexWrap: 'wrap',
  },
  subtitleItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 6 : (IS_WEB ? (IS_TABLET ? 12 : 10) : 14),
    paddingHorizontal: IS_MOBILE_WEB ? 8 : (IS_WEB ? (IS_TABLET ? 16 : 12) : 20),
    paddingVertical: IS_MOBILE_WEB ? 6 : (IS_WEB ? (IS_TABLET ? 10 : 8) : 12),
    borderRadius: IS_MOBILE_WEB ? 12 : (IS_WEB ? (IS_TABLET ? 20 : 16) : 24),
    backgroundColor: colors.backgroundTertiary,
    borderWidth: 1,
    borderColor: colors.info + '30',
  },
  subtitleItemGreen: {
    backgroundColor: colors.greenBright + '18',
    borderColor: colors.greenBright + '50',
  },
  subtitleIcon: {
    marginTop: IS_MOBILE_WEB ? 1 : 2,
  },
  subtitleText: {
    fontSize: IS_MOBILE_WEB ? 12 : (IS_WEB ? (IS_TABLET ? 24 : 18) : 28),
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: IS_MOBILE_WEB ? 14 : (IS_WEB ? (IS_TABLET ? 20 : 18) : 24),
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: IS_MOBILE_WEB ? 6 : (IS_WEB ? 8 : 12),
    maxWidth: IS_MOBILE_WEB ? '95%' : (IS_TABLET ? '70%' : '90%'),
    lineHeight: IS_MOBILE_WEB ? 20 : (IS_WEB ? 28 : 32),
    fontWeight: '500',
  },
  ctaRow: {
    flexDirection: 'row',
    gap: IS_MOBILE_WEB ? 10 : 16,
    marginTop: IS_MOBILE_WEB ? 24 : 40,
    justifyContent: 'center',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  contactButton: {
    flexDirection: 'row',
    gap: IS_MOBILE_WEB ? 8 : 12,
    alignItems: 'center',
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 28,
    paddingVertical: IS_MOBILE_WEB ? 12 : 18,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    minWidth: IS_MOBILE_WEB ? 140 : 200,
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
  },
  contactButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    letterSpacing: 0.3,
  },
  donationCtaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
    backgroundColor: colors.secondary,
    paddingVertical: IS_MOBILE_WEB ? 14 : 18,
    paddingHorizontal: IS_MOBILE_WEB ? 24 : 32,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    marginTop: IS_MOBILE_WEB ? 20 : 28,
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  donationCtaButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    letterSpacing: 0.3,
  },

  // Container / Screen
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContainer: {
    flex: 1,
  },
  content: {
    paddingBottom: IS_MOBILE_WEB ? 80 : 120,
    backgroundColor: colors.white,
  },

  // Stats
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    gap: IS_MOBILE_WEB ? 12 : 24,
    marginTop: IS_MOBILE_WEB ? 12 : 20,
    width: '100%',
  },
  statCard: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 250,
    maxWidth: IS_MOBILE_WEB ? '48%' : 300,
    paddingVertical: IS_MOBILE_WEB ? 16 : 32,
    paddingHorizontal: IS_MOBILE_WEB ? 12 : 20,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.white,
    alignItems: 'center',
    margin: IS_MOBILE_WEB ? 4 : 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
  },
  statIcon: {
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  statNumber: {
    fontSize: IS_MOBILE_WEB ? 22 : (IS_WEB ? 36 : 40),
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 6 : 8,
    letterSpacing: -1,
    textAlign: 'center',
  },
  statLabel: {
    fontSize: IS_MOBILE_WEB ? 12 : 18,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: IS_MOBILE_WEB ? 16 : 26,
    fontWeight: '500',
  },
  statsLoadingContainer: {
    paddingVertical: IS_MOBILE_WEB ? 40 : 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsLoadingText: {
    marginTop: IS_MOBILE_WEB ? 12 : 16,
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  statChevron: {
    position: 'absolute',
    bottom: IS_MOBILE_WEB ? 12 : 16,
    left: IS_MOBILE_WEB ? 12 : 16,
  },

  // Problems
  problemsContent: {
    gap: IS_MOBILE_WEB ? 20 : 32,
    marginTop: IS_MOBILE_WEB ? 16 : 24,
    width: '100%',
  },
  problemCard: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 20 : 32,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
  },
  problemIcon: {
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
    alignSelf: 'center',
  },
  problemTitle: {
    fontSize: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
    letterSpacing: -0.3,
  },
  problemText: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    lineHeight: IS_MOBILE_WEB ? 20 : 28,
    textAlign: 'right',
    fontWeight: '400',
  },

  // Features grid
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    gap: IS_MOBILE_WEB ? 12 : 24,
    width: '100%',
    marginTop: IS_MOBILE_WEB ? 12 : 20,
  },

  // How it works
  stepsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: IS_MOBILE_WEB ? 12 : 24,
    justifyContent: 'space-around',
    marginTop: IS_MOBILE_WEB ? 12 : 20,
    width: '100%',
  },
  stepCard: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 280,
    maxWidth: IS_MOBILE_WEB ? '100%' : 350,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.white,
    padding: IS_MOBILE_WEB ? 16 : 28,
    alignItems: 'center',
    margin: IS_MOBILE_WEB ? 4 : 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
  },
  stepNumberBadge: {
    position: 'absolute',
    top: IS_MOBILE_WEB ? -12 : -16,
    right: IS_MOBILE_WEB ? 16 : 24,
    width: IS_MOBILE_WEB ? 32 : 40,
    height: IS_MOBILE_WEB ? 32 : 40,
    borderRadius: IS_MOBILE_WEB ? 16 : 20,
    backgroundColor: colors.info,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  stepNumber: {
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    fontWeight: '900',
    color: colors.white,
  },
  stepTitle: {
    marginTop: IS_MOBILE_WEB ? 10 : 16,
    fontWeight: '800',
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 16 : 24,
    letterSpacing: -0.3,
  },
  stepText: {
    marginTop: IS_MOBILE_WEB ? 8 : 12,
    textAlign: 'center',
    color: colors.textSecondary,
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    lineHeight: IS_MOBILE_WEB ? 18 : 28,
    fontWeight: '400',
  },
  stepIcon: {
    marginTop: IS_MOBILE_WEB ? 12 : 16,
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
  },
  howItWorksNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 10 : 14,
    backgroundColor: colors.backgroundTertiary,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    padding: IS_MOBILE_WEB ? 16 : 24,
    marginTop: IS_MOBILE_WEB ? 24 : 32,
    borderLeftWidth: 4,
    borderLeftColor: colors.info,
    width: '100%',
    maxWidth: IS_TABLET ? 800 : '100%',
    alignSelf: 'center',
  },
  howItWorksNoteText: {
    flex: 1,
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textPrimary,
    lineHeight: IS_MOBILE_WEB ? 20 : 26,
    fontWeight: '500',
  },

  // Who is it for
  whoContent: {
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
  },
  whoMainCard: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 24 : 40,
    borderWidth: 2,
    borderColor: colors.info,
    shadowColor: colors.info,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    alignItems: 'center',
    marginBottom: IS_MOBILE_WEB ? 20 : 32,
  },
  whoMainIcon: {
    marginBottom: IS_MOBILE_WEB ? 16 : 24,
  },
  whoFutureCard: {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    padding: IS_MOBILE_WEB ? 20 : 28,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    borderStyle: 'dashed',
    alignItems: 'center',
  },
  whoFutureIcon: {
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
    opacity: 0.6,
  },
  whoFutureTitle: {
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    fontWeight: '700',
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  whoFutureText: {
    fontSize: IS_MOBILE_WEB ? 13 : 16,
    color: colors.textSecondary,
    lineHeight: IS_MOBILE_WEB ? 18 : 24,
    textAlign: 'center',
    fontWeight: '400',
  },
  splitTitle: {
    textAlign: 'center',
    fontSize: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  iconBullets: {
    marginTop: IS_MOBILE_WEB ? 10 : 16,
    gap: IS_MOBILE_WEB ? 10 : 16,
    width: '100%',
    maxWidth: IS_MOBILE_WEB ? '95%' : '90%',
    alignSelf: 'center',
  },
  iconBulletRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 10 : 16,
    justifyContent: 'center',
    paddingVertical: IS_MOBILE_WEB ? 2 : 4,
  },
  iconBulletText: {
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    textAlign: 'center',
    flex: 1,
  },

  // Values
  valuesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: IS_MOBILE_WEB ? 6 : 10,
    justifyContent: 'center',
    marginTop: IS_MOBILE_WEB ? 4 : 6,
  },
  valuePill: {
    paddingHorizontal: IS_MOBILE_WEB ? 14 : 24,
    paddingVertical: IS_MOBILE_WEB ? 8 : 14,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.info,
    margin: IS_MOBILE_WEB ? 3 : 6,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  valuePillText: {
    color: colors.info,
    fontWeight: '700',
    fontSize: IS_MOBILE_WEB ? 12 : 18,
  },
  trustList: {
    gap: IS_MOBILE_WEB ? 6 : 10,
    marginTop: IS_MOBILE_WEB ? 6 : 8,
    alignItems: 'center',
  },
  trustRow: {
    flexDirection: 'row-reverse',
    gap: IS_MOBILE_WEB ? 6 : 8,
    alignItems: 'center',
  },
  trustText: {
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 11 : 14,
  },

  // Core mottos
  coreMottosContainer: {
    marginTop: IS_MOBILE_WEB ? 20 : 32,
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
    gap: IS_MOBILE_WEB ? 20 : 28,
  },
  coreMottoItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: IS_MOBILE_WEB ? 12 : 16,
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 20 : 32,
    borderWidth: 2,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  coreMottoIcon: {
    marginLeft: IS_MOBILE_WEB ? 8 : 12,
    flexShrink: 0,
  },
  coreMottoText: {
    fontSize: IS_MOBILE_WEB ? 16 : (IS_WEB ? (IS_TABLET ? 22 : 20) : 24),
    color: colors.textPrimary,
    textAlign: 'right',
    fontWeight: '700',
    lineHeight: IS_MOBILE_WEB ? 24 : (IS_WEB ? 32 : 36),
    fontStyle: 'italic',
    flex: 1,
  },

  // Hierarchy
  hierarchyContainer: {
    marginTop: IS_MOBILE_WEB ? 16 : 24,
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
  },

  // Roadmap
  roadmapContainer: {
    marginTop: IS_MOBILE_WEB ? 24 : 32,
    width: '100%',
    maxWidth: IS_TABLET ? 1000 : '100%',
    alignSelf: 'center',
    writingDirection: 'rtl',
  },
  roadmapItemWrapper: {
    width: '100%',
    marginBottom: 0,
  },
  roadmapItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 20,
    padding: IS_MOBILE_WEB ? 16 : 24,
    marginBottom: IS_MOBILE_WEB ? 20 : 24,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.backgroundSecondary,
    writingDirection: 'rtl',
  },
  roadmapIconContainer: {
    width: IS_MOBILE_WEB ? 48 : 64,
    height: IS_MOBILE_WEB ? 48 : 64,
    borderRadius: IS_MOBILE_WEB ? 24 : 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: IS_MOBILE_WEB ? 12 : 16,
    flexShrink: 0,
  },
  roadmapContent: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  roadmapTimeBadge: {
    paddingHorizontal: IS_MOBILE_WEB ? 12 : 16,
    paddingVertical: IS_MOBILE_WEB ? 6 : 8,
    borderRadius: IS_MOBILE_WEB ? 8 : 12,
    alignSelf: 'flex-end',
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  roadmapTimeText: {
    color: colors.white,
    fontWeight: '900',
    fontSize: IS_MOBILE_WEB ? 14 : 16,
    letterSpacing: 0.5,
  },
  roadmapLabel: {
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    lineHeight: IS_MOBILE_WEB ? 24 : 30,
    fontWeight: '700',
    textAlign: 'right',
  },
  roadmapConnector: {
    position: 'absolute',
    right: IS_MOBILE_WEB ? 24 : 32,
    top: IS_MOBILE_WEB ? 64 : 88,
    height: IS_MOBILE_WEB ? 20 : 24,
    width: 2,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 0,
  },
  roadmapConnectorLine: {
    width: 2,
    height: '100%',
    borderLeftWidth: 2,
    borderStyle: 'dashed',
  },
  logoEvolutionContainer: {
    marginTop: IS_MOBILE_WEB ? 32 : 48,
    width: '100%',
    alignItems: 'center',
  },
  logoEvolutionTitle: {
    fontSize: IS_MOBILE_WEB ? 20 : 28,
    fontWeight: '900',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  logoEvolutionSubtitle: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 20 : 28,
    fontWeight: '500',
  },
  logoEvolutionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 12 : 20,
    width: '100%',
    maxWidth: IS_TABLET ? 800 : '100%',
  },
  logoEvolutionItem: {
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 100 : 140,
    maxWidth: IS_MOBILE_WEB ? 120 : 160,
  },
  logoEvolutionImage: {
    width: IS_MOBILE_WEB ? 80 : 120,
    height: IS_MOBILE_WEB ? 80 : 120,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    borderWidth: 2,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.white,
  },
  logoEvolutionLabel: {
    fontSize: IS_MOBILE_WEB ? 12 : 14,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  brandStrip: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 8 : 10,
    paddingVertical: IS_MOBILE_WEB ? 12 : 16,
  },

  // About / GitHub
  githubLinkContainer: {
    marginTop: IS_MOBILE_WEB ? 24 : 32,
    width: '100%',
    maxWidth: IS_TABLET ? 600 : '100%',
    alignSelf: 'center',
  },
  githubLinkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 20,
    padding: IS_MOBILE_WEB ? 20 : 28,
    borderWidth: 2,
    borderColor: colors.info,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    gap: IS_MOBILE_WEB ? 12 : 16,
  },
  githubLinkTextContainer: {
    flex: 1,
    gap: IS_MOBILE_WEB ? 4 : 6,
  },
  githubLinkTitle: {
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 4 : 6,
  },
  githubLinkDescription: {
    fontSize: IS_MOBILE_WEB ? 13 : 16,
    color: colors.textSecondary,
    lineHeight: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '400',
  },

  // Gallery
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 8 : 16,
    marginTop: IS_MOBILE_WEB ? 12 : 20,
  },
  galleryImage: {
    width: IS_MOBILE_WEB ? 140 : 280,
    height: IS_MOBILE_WEB ? 140 : 280,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.backgroundSecondary,
  },

  // Partners
  partnersContainer: {
    width: '100%',
    maxWidth: IS_TABLET ? 800 : '100%',
    alignSelf: 'center',
    marginTop: IS_MOBILE_WEB ? 12 : 20,
  },
  partnerCard: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 24 : 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    maxWidth: IS_MOBILE_WEB ? '100%' : 400,
    alignSelf: 'center',
  },
  partnerLogo: {
    height: IS_MOBILE_WEB ? 50 : 70,
    width: IS_MOBILE_WEB ? 120 : 180,
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
  },

  // FAQ
  faqContainer: {
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
    gap: IS_MOBILE_WEB ? 12 : 16,
    marginTop: IS_MOBILE_WEB ? 12 : 20,
  },
  faqCard: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
    overflow: 'hidden',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  faqQuestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: IS_MOBILE_WEB ? 16 : 20,
    backgroundColor: colors.backgroundSecondary,
  },
  faqQuestionContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 10 : 14,
  },
  faqIcon: {
    marginRight: IS_MOBILE_WEB ? 4 : 6,
  },
  faqQ: {
    flex: 1,
    fontWeight: '800',
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 15 : 18,
    lineHeight: IS_MOBILE_WEB ? 22 : 26,
  },
  faqAnswerContainer: {
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 20,
    paddingBottom: IS_MOBILE_WEB ? 16 : 20,
    overflow: 'hidden',
  },
  faqA: {
    color: colors.textSecondary,
    fontSize: IS_MOBILE_WEB ? 14 : 16,
    lineHeight: IS_MOBILE_WEB ? 20 : 24,
    fontWeight: '400',
  },

  // Contact
  contactRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: IS_MOBILE_WEB ? 10 : 20,
    justifyContent: 'center',
    marginTop: IS_MOBILE_WEB ? 16 : 24,
    width: '100%',
  },

  // Instagram
  instagramContainer: {
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
    marginTop: IS_MOBILE_WEB ? 12 : 20,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    overflow: 'hidden',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  instagramWebViewContainer: {
    width: '100%',
    height: IS_MOBILE_WEB ? 500 : 600,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    overflow: 'hidden',
  },
  instagramWebView: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  instagramLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
    gap: IS_MOBILE_WEB ? 12 : 16,
  },
  instagramLoadingText: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  instagramFallback: {
    padding: IS_MOBILE_WEB ? 40 : 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 16 : 24,
  },
  instagramFallbackText: {
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    color: colors.textPrimary,
    fontWeight: '600',
    textAlign: 'center',
  },

  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.dropdownModalOverlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: IS_MOBILE_WEB ? 16 : 24,
  },
  modalContainer: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    width: '100%',
    maxWidth: IS_TABLET ? 800 : (IS_MOBILE_WEB ? '95%' : 600),
    maxHeight: '85%',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: IS_MOBILE_WEB ? 16 : 24,
    borderBottomWidth: 1,
    borderBottomColor: colors.backgroundTertiary,
    backgroundColor: colors.backgroundTertiary,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 12 : 16,
    flex: 1,
  },
  modalTitleContainer: {
    flex: 1,
  },
  modalTitle: {
    fontSize: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 4 : 6,
  },
  modalSubtitle: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    fontWeight: '600',
    color: colors.info,
  },
  modalCloseButton: {
    padding: IS_MOBILE_WEB ? 4 : 8,
    marginRight: IS_MOBILE_WEB ? -4 : -8,
  },
  modalContent: {
    flex: 1,
  },
  modalLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: IS_MOBILE_WEB ? 40 : 60,
  },
  modalLoadingText: {
    marginTop: IS_MOBILE_WEB ? 12 : 16,
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  modalEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: IS_MOBILE_WEB ? 40 : 60,
  },
  modalEmptyText: {
    marginTop: IS_MOBILE_WEB ? 16 : 24,
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  detailList: {
    padding: IS_MOBILE_WEB ? 16 : 24,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: IS_MOBILE_WEB ? 12 : 16,
    paddingHorizontal: IS_MOBILE_WEB ? 12 : 16,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    backgroundColor: colors.backgroundSecondary,
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
  },
  detailItemNumber: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    fontWeight: '700',
    color: colors.info,
    marginLeft: IS_MOBILE_WEB ? 8 : 12,
    minWidth: IS_MOBILE_WEB ? 24 : 32,
  },
  detailItemContent: {
    flex: 1,
  },
  detailItemText: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 4 : 6,
    lineHeight: IS_MOBILE_WEB ? 20 : 24,
  },
  detailItemSubtext: {
    fontSize: IS_MOBILE_WEB ? 12 : 14,
    color: colors.textSecondary,
    lineHeight: IS_MOBILE_WEB ? 16 : 20,
    marginTop: IS_MOBILE_WEB ? 2 : 4,
  },

  // Donation modal
  donationModalContainer: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 20 : 28,
    width: '100%',
    maxWidth: IS_TABLET ? 500 : (IS_MOBILE_WEB ? '90%' : 450),
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
    overflow: 'hidden',
  },
  donationModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: IS_MOBILE_WEB ? 20 : 28,
    borderBottomWidth: 1,
    borderBottomColor: colors.backgroundTertiary,
    backgroundColor: colors.backgroundTertiary,
  },
  donationModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 12 : 16,
    flex: 1,
  },
  donationModalTitleContainer: {
    flex: 1,
  },
  donationModalTitle: {
    fontSize: IS_MOBILE_WEB ? 20 : 28,
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 4 : 6,
  },
  donationModalSubtitle: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  donationModalContent: {
    padding: IS_MOBILE_WEB ? 20 : 28,
  },
  donationMessageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: IS_MOBILE_WEB ? 12 : 16,
    backgroundColor: colors.backgroundTertiary,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    padding: IS_MOBILE_WEB ? 16 : 20,
    marginBottom: IS_MOBILE_WEB ? 20 : 24,
    borderLeftWidth: 4,
    borderLeftColor: colors.info,
  },
  donationMessageText: {
    flex: 1,
    fontSize: IS_MOBILE_WEB ? 15 : 18,
    color: colors.textPrimary,
    lineHeight: IS_MOBILE_WEB ? 22 : 26,
    fontWeight: '600',
  },
  donationButtonsContainer: {
    flexDirection: 'row',
    gap: IS_MOBILE_WEB ? 10 : 16,
    marginBottom: IS_MOBILE_WEB ? 16 : 20,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  donationButton: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 100 : 120,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
    paddingVertical: IS_MOBILE_WEB ? 14 : 18,
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 20,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  donationButtonWhatsApp: {
    backgroundColor: colors.success,
  },
  donationButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    letterSpacing: 0.3,
  },
  donationNoteText: {
    fontSize: IS_MOBILE_WEB ? 13 : 16,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '400',
    fontStyle: 'italic',
  },

  // Footer
  footer: {
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 20,
    paddingVertical: IS_MOBILE_WEB ? 20 : 32,
    borderTopWidth: 1,
    borderTopColor: colors.backgroundSecondary,
    alignItems: 'center',
    marginTop: IS_MOBILE_WEB ? 24 : 40,
    backgroundColor: colors.backgroundSecondary,
  },
  footerText: {
    color: colors.textSecondary,
    fontSize: IS_MOBILE_WEB ? 12 : 14,
    fontWeight: '500',
  },
});

export { styles };
