/**
 * StyleSheet for the marketing landing site screen and its sections.
 */
import { StyleSheet } from 'react-native';
import colors from '../../globals/colors';
import { landingSharedStyleSheet } from './styles';
import { IS_WEB, IS_MOBILE_WEB, IS_TABLET, SCREEN_WIDTH } from './constants';

/** Non-nested font size for CTA labels (avoids Sonar nested-ternary noise). */
const ctaPillTextFontSize = IS_MOBILE_WEB ? 14 : IS_WEB ? 18 : 20;

export const landingSiteScreenStyles = StyleSheet.create({
  ...landingSharedStyleSheet,
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContainer: {
    flex: 1,
  },
  content: {
    paddingBottom: IS_MOBILE_WEB ? 80 : 120,
    backgroundColor: colors.white,
  },
  heroMottosContainer: {
    marginTop: IS_MOBILE_WEB ? 16 : 24,
    width: '100%',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
  },
  mottoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
    maxWidth: IS_MOBILE_WEB ? '95%' : '85%',
  },
  mottoItemIcon: {
    marginTop: IS_MOBILE_WEB ? 2 : 4,
  },
  mottoSubtitle: {
    fontSize: IS_MOBILE_WEB ? 16 : (IS_WEB ? (IS_TABLET ? 22 : 20) : 26),
    color: colors.textPrimary,
    textAlign: 'center',
    fontWeight: '700',
    lineHeight: IS_MOBILE_WEB ? 24 : (IS_WEB ? 32 : 36),
    fontStyle: 'italic',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    flex: 1,
  },
  ctaIcon: {
    marginRight: IS_MOBILE_WEB ? 6 : 8,
  },
  primaryCta: {
    backgroundColor: colors.info,
    paddingHorizontal: IS_MOBILE_WEB ? 20 : 32,
    paddingVertical: IS_MOBILE_WEB ? 12 : 18,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    minWidth: IS_MOBILE_WEB ? 140 : 200,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.info,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 12,
    elevation: 8,
  },
  primaryCtaText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: ctaPillTextFontSize,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  secondaryCta: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.info,
    paddingHorizontal: IS_MOBILE_WEB ? 20 : 32,
    paddingVertical: IS_MOBILE_WEB ? 12 : 18,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    minWidth: IS_MOBILE_WEB ? 140 : 200,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  secondaryCtaText: {
    color: colors.info,
    fontWeight: '800',
    fontSize: ctaPillTextFontSize,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  sectionSubTitle: {
    fontSize: IS_MOBILE_WEB ? 14 : (IS_WEB ? 18 : 24),
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
    marginTop: IS_MOBILE_WEB ? 10 : (IS_WEB ? 15 : 20),
    marginBottom: IS_MOBILE_WEB ? 6 : (IS_WEB ? 8 : 12)
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    gap: IS_MOBILE_WEB ? 12 : 24,
    width: '100%',
    marginTop: IS_MOBILE_WEB ? 12 : 20,
  },
  paragraph: {
    fontSize: IS_MOBILE_WEB ? 14 : (IS_WEB ? 18 : 20),
    color: colors.textPrimary,
    lineHeight: IS_MOBILE_WEB ? 20 : (IS_WEB ? 28 : 30),
    textAlign: 'center',
    marginTop: IS_MOBILE_WEB ? 8 : 12,
    maxWidth: IS_MOBILE_WEB ? '95%' : (IS_TABLET ? '80%' : '90%'),
    alignSelf: 'center',
    fontWeight: '400',
  },
  linksRow: { flexDirection: 'row', gap: IS_MOBILE_WEB ? 12 : 24, marginTop: IS_MOBILE_WEB ? 10 : 16, alignSelf: 'center', flexWrap: 'wrap', justifyContent: 'center' },
  link: { color: colors.primary, fontWeight: '700', fontSize: IS_MOBILE_WEB ? 14 : 20, padding: IS_MOBILE_WEB ? 6 : 8 },
  faqContainer: {
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
    gap: IS_MOBILE_WEB ? 12 : 16,
    marginTop: IS_MOBILE_WEB ? 12 : 20,
  },
  faqCard: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
    overflow: 'hidden',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  faqQuestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: IS_MOBILE_WEB ? 16 : 20,
    backgroundColor: colors.backgroundSecondary,
  },
  faqQuestionContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 10 : 14,
  },
  faqIcon: {
    marginRight: IS_MOBILE_WEB ? 4 : 6,
  },
  faqQ: {
    flex: 1,
    fontWeight: '800',
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 15 : 18,
    lineHeight: IS_MOBILE_WEB ? 22 : 26,
  },
  faqAnswerContainer: {
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 20,
    paddingBottom: IS_MOBILE_WEB ? 16 : 20,
    overflow: 'hidden',
  },
  faqA: {
    color: colors.textSecondary,
    fontSize: IS_MOBILE_WEB ? 14 : 16,
    lineHeight: IS_MOBILE_WEB ? 20 : 24,
    fontWeight: '400',
  },
  iconBullets: { marginTop: IS_MOBILE_WEB ? 10 : 16, gap: IS_MOBILE_WEB ? 10 : 16, width: '100%', maxWidth: IS_MOBILE_WEB ? '95%' : '90%', alignSelf: 'center' },
  iconBulletRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: IS_MOBILE_WEB ? 10 : 16, justifyContent: 'center', paddingVertical: IS_MOBILE_WEB ? 2 : 4 },
  iconBulletText: { color: colors.textPrimary, fontSize: IS_MOBILE_WEB ? 13 : 18, textAlign: 'center', flex: 1 },
  stepsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: IS_MOBILE_WEB ? 12 : 24, justifyContent: 'space-around', marginTop: IS_MOBILE_WEB ? 12 : 20, width: '100%' },
  stepCard: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 280,
    maxWidth: IS_MOBILE_WEB ? '100%' : 350,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.white,
    padding: IS_MOBILE_WEB ? 16 : 28,
    alignItems: 'center',
    margin: IS_MOBILE_WEB ? 4 : 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
  },
  stepTitle: {
    marginTop: IS_MOBILE_WEB ? 10 : 16,
    fontWeight: '800',
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 16 : 24,
    letterSpacing: -0.3,
  },
  stepText: {
    marginTop: IS_MOBILE_WEB ? 8 : 12,
    textAlign: 'center',
    color: colors.textSecondary,
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    lineHeight: IS_MOBILE_WEB ? 18 : 28,
    fontWeight: '400',
  },
  splitRow: { flexDirection: 'row', flexWrap: 'wrap', gap: IS_MOBILE_WEB ? 16 : 30, justifyContent: 'space-around', width: '100%' },
  splitColumn: { flex: 1, minWidth: IS_MOBILE_WEB ? 140 : 320, maxWidth: IS_MOBILE_WEB ? '100%' : 500, padding: IS_MOBILE_WEB ? 12 : 20 },
  splitTitle: { textAlign: 'center', fontSize: IS_MOBILE_WEB ? 18 : 24, fontWeight: '800', color: colors.textPrimary, marginBottom: IS_MOBILE_WEB ? 8 : 12 },
  valuesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: IS_MOBILE_WEB ? 6 : 10, justifyContent: 'center', marginTop: IS_MOBILE_WEB ? 4 : 6 },
  valuePill: {
    paddingHorizontal: IS_MOBILE_WEB ? 14 : 24,
    paddingVertical: IS_MOBILE_WEB ? 8 : 14,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.info,
    margin: IS_MOBILE_WEB ? 3 : 6,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  valuePillText: {
    color: colors.info,
    fontWeight: '700',
    fontSize: IS_MOBILE_WEB ? 12 : 18,
  },
  roadmapContainer: {
    marginTop: IS_MOBILE_WEB ? 24 : 32,
    width: '100%',
    maxWidth: IS_TABLET ? 1000 : '100%',
    alignSelf: 'center',
    writingDirection: 'rtl',
  },
  roadmapItemWrapper: {
    width: '100%',
    marginBottom: 0,
  },
  roadmapItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 20,
    padding: IS_MOBILE_WEB ? 16 : 24,
    marginBottom: IS_MOBILE_WEB ? 20 : 24,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.backgroundSecondary,
    writingDirection: 'rtl',
  },
  roadmapIconContainer: {
    width: IS_MOBILE_WEB ? 48 : 64,
    height: IS_MOBILE_WEB ? 48 : 64,
    borderRadius: IS_MOBILE_WEB ? 24 : 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: IS_MOBILE_WEB ? 12 : 16,
    flexShrink: 0,
  },
  roadmapContent: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  roadmapTimeBadge: {
    paddingHorizontal: IS_MOBILE_WEB ? 12 : 16,
    paddingVertical: IS_MOBILE_WEB ? 6 : 8,
    borderRadius: IS_MOBILE_WEB ? 8 : 12,
    alignSelf: 'flex-end',
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  roadmapTimeText: {
    color: colors.white,
    fontWeight: '900',
    fontSize: IS_MOBILE_WEB ? 14 : 16,
    letterSpacing: 0.5,
  },
  roadmapLabel: {
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    lineHeight: IS_MOBILE_WEB ? 24 : 30,
    fontWeight: '700',
    textAlign: 'right',
  },
  roadmapConnector: {
    position: 'absolute',
    right: IS_MOBILE_WEB ? 24 : 32,
    top: IS_MOBILE_WEB ? 64 : 88,
    height: IS_MOBILE_WEB ? 20 : 24,
    width: 2,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 0,
  },
  roadmapConnectorLine: {
    width: 2,
    height: '100%',
    borderLeftWidth: 2,
    borderStyle: 'dashed',
  },
  logoEvolutionContainer: {
    marginTop: IS_MOBILE_WEB ? 32 : 48,
    width: '100%',
    alignItems: 'center',
  },
  logoEvolutionTitle: {
    fontSize: IS_MOBILE_WEB ? 20 : 28,
    fontWeight: '900',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  logoEvolutionSubtitle: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 20 : 28,
    fontWeight: '500',
  },
  logoEvolutionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 12 : 20,
    width: '100%',
    maxWidth: IS_TABLET ? 800 : '100%',
  },
  logoEvolutionItem: {
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 100 : 140,
    maxWidth: IS_MOBILE_WEB ? 120 : 160,
  },
  logoEvolutionImage: {
    width: IS_MOBILE_WEB ? 80 : 120,
    height: IS_MOBILE_WEB ? 80 : 120,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    borderWidth: 2,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.white,
  },
  logoEvolutionLabel: {
    fontSize: IS_MOBILE_WEB ? 12 : 14,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  brandStrip: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: IS_MOBILE_WEB ? 8 : 10, paddingVertical: IS_MOBILE_WEB ? 12 : 16 },
  brandIcon: { width: IS_MOBILE_WEB ? 30 : 40, height: IS_MOBILE_WEB ? 30 : 40, opacity: 0.9 },
  contactRow: { flexDirection: 'row', flexWrap: 'wrap', gap: IS_MOBILE_WEB ? 10 : 20, justifyContent: 'center', marginTop: IS_MOBILE_WEB ? 16 : 24, width: '100%' },
  footer: {
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 20,
    paddingVertical: IS_MOBILE_WEB ? 20 : 32,
    borderTopWidth: 1,
    borderTopColor: colors.backgroundSecondary,
    alignItems: 'center',
    marginTop: IS_MOBILE_WEB ? 24 : 40,
    backgroundColor: colors.backgroundSecondary,
  },
  footerText: {
    color: colors.textSecondary,
    fontSize: IS_MOBILE_WEB ? 12 : 14,
    fontWeight: '500',
  },
  // Statistics styles
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    gap: IS_MOBILE_WEB ? 12 : 24,
    marginTop: IS_MOBILE_WEB ? 12 : 20,
    width: '100%'
  },
  statCard: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 250,
    maxWidth: IS_MOBILE_WEB ? '48%' : 300,
    paddingVertical: IS_MOBILE_WEB ? 16 : 32,
    paddingHorizontal: IS_MOBILE_WEB ? 12 : 20,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.white,
    alignItems: 'center',
    margin: IS_MOBILE_WEB ? 4 : 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
  },
  statIcon: {
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  statNumber: {
    fontSize: IS_MOBILE_WEB ? 22 : (IS_WEB ? 36 : 40),
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 6 : 8,
    letterSpacing: -1,
    textAlign: 'center',
  },
  statLabel: {
    fontSize: IS_MOBILE_WEB ? 12 : 18,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: IS_MOBILE_WEB ? 16 : 26,
    fontWeight: '500',
  },
  statsLoadingContainer: {
    paddingVertical: IS_MOBILE_WEB ? 40 : 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsLoadingText: {
    marginTop: IS_MOBILE_WEB ? 12 : 16,
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  useCases: { gap: IS_MOBILE_WEB ? 10 : 16, marginTop: IS_MOBILE_WEB ? 10 : 16, alignSelf: 'center', width: '100%', maxWidth: IS_MOBILE_WEB ? '95%' : '90%' },
  useCaseRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: IS_MOBILE_WEB ? 10 : 16, alignSelf: 'center', paddingVertical: IS_MOBILE_WEB ? 4 : 8 },
  useCaseText: { color: colors.textPrimary, fontSize: IS_MOBILE_WEB ? 13 : 18, textAlign: 'center', flex: 1 },
  testimonials: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-around', gap: IS_MOBILE_WEB ? 12 : 24, marginTop: IS_MOBILE_WEB ? 12 : 20, width: '100%' },
  testimonialCard: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 320,
    maxWidth: IS_MOBILE_WEB ? '100%' : 400,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.white,
    padding: IS_MOBILE_WEB ? 16 : 28,
    margin: IS_MOBILE_WEB ? 4 : 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 6,
  },
  testimonialText: {
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    lineHeight: IS_MOBILE_WEB ? 18 : 30,
    textAlign: 'center',
    fontStyle: 'italic',
    fontWeight: '400',
  },
  testimonialUser: {
    color: colors.textSecondary,
    marginTop: IS_MOBILE_WEB ? 10 : 16,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: IS_MOBILE_WEB ? 12 : 16,
  },
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 8 : 16,
    marginTop: IS_MOBILE_WEB ? 12 : 20
  },
  galleryImage: {
    width: IS_MOBILE_WEB ? 140 : 280,
    height: IS_MOBILE_WEB ? 140 : 280,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.backgroundSecondary
  },
  partnersContainer: {
    width: '100%',
    maxWidth: IS_TABLET ? 800 : '100%',
    alignSelf: 'center',
    marginTop: IS_MOBILE_WEB ? 12 : 20,
  },
  partnersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 20 : 40,
    marginTop: IS_MOBILE_WEB ? 12 : 20,
    flexWrap: 'wrap'
  },
  partnerCard: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 24 : 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    maxWidth: IS_MOBILE_WEB ? '100%' : 400,
    alignSelf: 'center',
  },
  partnerLogo: {
    height: IS_MOBILE_WEB ? 50 : 70,
    width: IS_MOBILE_WEB ? 120 : 180,
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
  },
  partnerName: {
    fontSize: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  partnerDescription: {
    fontSize: IS_MOBILE_WEB ? 14 : 16,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: IS_MOBILE_WEB ? 20 : 24,
  },
  instagramContainer: {
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
    marginTop: IS_MOBILE_WEB ? 12 : 20,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    overflow: 'hidden',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  instagramEmbedContainer: {
    width: '100%',
    height: IS_MOBILE_WEB ? 500 : 600,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    overflow: 'hidden',
  },
  instagramWebViewContainer: {
    width: '100%',
    height: IS_MOBILE_WEB ? 500 : 600,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    overflow: 'hidden',
  },
  instagramWebView: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  instagramLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
    gap: IS_MOBILE_WEB ? 12 : 16,
  },
  instagramLoadingText: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  instagramFallback: {
    padding: IS_MOBILE_WEB ? 40 : 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 16 : 24,
  },
  instagramFallbackText: {
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    color: colors.textPrimary,
    fontWeight: '600',
    textAlign: 'center',
  },
  trustList: { gap: IS_MOBILE_WEB ? 6 : 10, marginTop: IS_MOBILE_WEB ? 6 : 8, alignItems: 'center' },
  trustRow: { flexDirection: 'row-reverse', gap: IS_MOBILE_WEB ? 6 : 8, alignItems: 'center' },
  trustText: { color: colors.textPrimary, fontSize: IS_MOBILE_WEB ? 11 : 14 },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: IS_MOBILE_WEB ? 8 : 12, marginTop: IS_MOBILE_WEB ? 6 : 8 },
  categoryCard: {
    width: IS_MOBILE_WEB ? 100 : 150,
    height: IS_MOBILE_WEB ? 60 : 90,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 4 : 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  categoryText: {
    fontWeight: '700',
    color: colors.textPrimary,
    fontSize: IS_MOBILE_WEB ? 12 : 16,
  },
  menuMinimizeButton: {
    padding: SCREEN_WIDTH * 0.002, // 0.2% of screen width
  },
  sectionAltBackground: {
    backgroundColor: colors.backgroundSecondary,
  },
  emphasis: {
    fontWeight: '800',
    color: colors.info,
  },
  visionHighlights: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 16 : 24,
    marginTop: IS_MOBILE_WEB ? 20 : 32,
    width: '100%',
  },
  visionHighlight: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 200,
    maxWidth: IS_MOBILE_WEB ? '100%' : 250,
    alignItems: 'center',
    padding: IS_MOBILE_WEB ? 16 : 24,
    gap: IS_MOBILE_WEB ? 8 : 12,
  },
  visionHighlightText: {
    fontSize: IS_MOBILE_WEB ? 13 : 16,
    color: colors.textPrimary,
    textAlign: 'center',
    fontWeight: '600',
  },
  problemsContent: {
    gap: IS_MOBILE_WEB ? 20 : 32,
    marginTop: IS_MOBILE_WEB ? 16 : 24,
    width: '100%',
  },
  problemCard: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 20 : 32,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
  },
  problemIcon: {
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
    alignSelf: 'center',
  },
  problemTitle: {
    fontSize: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
    letterSpacing: -0.3,
  },
  problemText: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    lineHeight: IS_MOBILE_WEB ? 20 : 28,
    textAlign: 'right',
    fontWeight: '400',
  },
  whoContent: {
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
  },
  whoMainCard: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 24 : 40,
    borderWidth: 2,
    borderColor: colors.info,
    shadowColor: colors.info,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    alignItems: 'center',
    marginBottom: IS_MOBILE_WEB ? 20 : 32,
  },
  whoMainIcon: {
    marginBottom: IS_MOBILE_WEB ? 16 : 24,
  },
  whoFutureCard: {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: IS_MOBILE_WEB ? 12 : 20,
    padding: IS_MOBILE_WEB ? 20 : 28,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
    borderStyle: 'dashed',
    alignItems: 'center',
  },
  whoFutureIcon: {
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
    opacity: 0.6,
  },
  whoFutureTitle: {
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    fontWeight: '700',
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
  },
  whoFutureText: {
    fontSize: IS_MOBILE_WEB ? 13 : 16,
    color: colors.textSecondary,
    lineHeight: IS_MOBILE_WEB ? 18 : 24,
    textAlign: 'center',
    fontWeight: '400',
  },
  githubLinkContainer: {
    marginTop: IS_MOBILE_WEB ? 24 : 32,
    width: '100%',
    maxWidth: IS_TABLET ? 600 : '100%',
    alignSelf: 'center',
  },
  githubLinkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 20,
    padding: IS_MOBILE_WEB ? 20 : 28,
    borderWidth: 2,
    borderColor: colors.info,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    gap: IS_MOBILE_WEB ? 12 : 16,
  },
  githubLinkTextContainer: {
    flex: 1,
    gap: IS_MOBILE_WEB ? 4 : 6,
  },
  githubLinkTitle: {
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 4 : 6,
  },
  githubLinkDescription: {
    fontSize: IS_MOBILE_WEB ? 13 : 16,
    color: colors.textSecondary,
    lineHeight: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '400',
  },
  mottoContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 16 : 24,
    marginTop: IS_MOBILE_WEB ? 20 : 32,
    marginBottom: IS_MOBILE_WEB ? 20 : 32,
    width: '100%',
  },
  mottoCard: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 140 : 280,
    maxWidth: IS_MOBILE_WEB ? '100%' : 400,
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 20 : 32,
    borderWidth: 2,
    borderColor: colors.info,
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 12 : 16,
    shadowColor: colors.info,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 6,
  },
  mottoIcon: {
    marginBottom: IS_MOBILE_WEB ? 4 : 8,
  },
  mottoText: {
    fontSize: IS_MOBILE_WEB ? 16 : 22,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: IS_MOBILE_WEB ? 22 : 30,
  },
  coreMottosContainer: {
    marginTop: IS_MOBILE_WEB ? 20 : 32,
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
    gap: IS_MOBILE_WEB ? 20 : 28,
  },
  hierarchyContainer: {
    marginTop: IS_MOBILE_WEB ? 16 : 24,
    width: '100%',
    maxWidth: IS_TABLET ? 900 : '100%',
    alignSelf: 'center',
  },
  coreMottoItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: IS_MOBILE_WEB ? 12 : 16,
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    padding: IS_MOBILE_WEB ? 20 : 32,
    borderWidth: 2,
    borderColor: colors.backgroundTertiary,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  coreMottoIcon: {
    marginLeft: IS_MOBILE_WEB ? 8 : 12,
    flexShrink: 0,
  },
  coreMottoText: {
    fontSize: IS_MOBILE_WEB ? 16 : (IS_WEB ? (IS_TABLET ? 22 : 20) : 24),
    color: colors.textPrimary,
    textAlign: 'right',
    fontWeight: '700',
    lineHeight: IS_MOBILE_WEB ? 24 : (IS_WEB ? 32 : 36),
    fontStyle: 'italic',
    flex: 1,
  },
  stepNumberBadge: {
    position: 'absolute',
    top: IS_MOBILE_WEB ? -12 : -16,
    right: IS_MOBILE_WEB ? 16 : 24,
    width: IS_MOBILE_WEB ? 32 : 40,
    height: IS_MOBILE_WEB ? 32 : 40,
    borderRadius: IS_MOBILE_WEB ? 16 : 20,
    backgroundColor: colors.info,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  stepNumber: {
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    fontWeight: '900',
    color: colors.white,
  },
  stepIcon: {
    marginTop: IS_MOBILE_WEB ? 12 : 16,
    marginBottom: IS_MOBILE_WEB ? 12 : 16,
  },
  statChevron: {
    position: 'absolute',
    bottom: IS_MOBILE_WEB ? 12 : 16,
    left: IS_MOBILE_WEB ? 12 : 16,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: IS_MOBILE_WEB ? 16 : 24,
  },
  modalContainer: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 16 : 24,
    width: '100%',
    maxWidth: IS_TABLET ? 800 : (IS_MOBILE_WEB ? '95%' : 600),
    maxHeight: '85%',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: IS_MOBILE_WEB ? 16 : 24,
    borderBottomWidth: 1,
    borderBottomColor: colors.backgroundTertiary,
    backgroundColor: colors.backgroundTertiary,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 12 : 16,
    flex: 1,
  },
  modalTitleContainer: {
    flex: 1,
  },
  modalTitle: {
    fontSize: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 4 : 6,
  },
  modalSubtitle: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    fontWeight: '600',
    color: colors.info,
  },
  modalCloseButton: {
    padding: IS_MOBILE_WEB ? 4 : 8,
    marginRight: IS_MOBILE_WEB ? -4 : -8,
  },
  modalContent: {
    flex: 1,
  },
  modalLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: IS_MOBILE_WEB ? 40 : 60,
  },
  modalLoadingText: {
    marginTop: IS_MOBILE_WEB ? 12 : 16,
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  modalEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: IS_MOBILE_WEB ? 40 : 60,
  },
  modalEmptyText: {
    marginTop: IS_MOBILE_WEB ? 16 : 24,
    fontSize: IS_MOBILE_WEB ? 16 : 20,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  detailList: {
    padding: IS_MOBILE_WEB ? 16 : 24,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: IS_MOBILE_WEB ? 12 : 16,
    paddingHorizontal: IS_MOBILE_WEB ? 12 : 16,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    backgroundColor: colors.backgroundSecondary,
    marginBottom: IS_MOBILE_WEB ? 8 : 12,
    borderWidth: 1,
    borderColor: colors.backgroundTertiary,
  },
  detailItemNumber: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    fontWeight: '700',
    color: colors.info,
    marginLeft: IS_MOBILE_WEB ? 8 : 12,
    minWidth: IS_MOBILE_WEB ? 24 : 32,
  },
  detailItemContent: {
    flex: 1,
  },
  detailItemText: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 4 : 6,
    lineHeight: IS_MOBILE_WEB ? 20 : 24,
  },
  detailItemSubtext: {
    fontSize: IS_MOBILE_WEB ? 12 : 14,
    color: colors.textSecondary,
    lineHeight: IS_MOBILE_WEB ? 16 : 20,
    marginTop: IS_MOBILE_WEB ? 2 : 4,
  },
  howItWorksNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 10 : 14,
    backgroundColor: colors.backgroundTertiary,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    padding: IS_MOBILE_WEB ? 16 : 24,
    marginTop: IS_MOBILE_WEB ? 24 : 32,
    borderLeftWidth: 4,
    borderLeftColor: colors.info,
    width: '100%',
    maxWidth: IS_TABLET ? 800 : '100%',
    alignSelf: 'center',
  },
  howItWorksNoteText: {
    flex: 1,
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    color: colors.textPrimary,
    lineHeight: IS_MOBILE_WEB ? 20 : 26,
    fontWeight: '500',
  },
  // Donation Modal Styles
  donationModalContainer: {
    backgroundColor: colors.white,
    borderRadius: IS_MOBILE_WEB ? 20 : 28,
    width: '100%',
    maxWidth: IS_TABLET ? 500 : (IS_MOBILE_WEB ? '90%' : 450),
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
    overflow: 'hidden',
  },
  donationModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: IS_MOBILE_WEB ? 20 : 28,
    borderBottomWidth: 1,
    borderBottomColor: colors.backgroundTertiary,
    backgroundColor: colors.backgroundTertiary,
  },
  donationModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: IS_MOBILE_WEB ? 12 : 16,
    flex: 1,
  },
  donationModalTitleContainer: {
    flex: 1,
  },
  donationModalTitle: {
    fontSize: IS_MOBILE_WEB ? 20 : 28,
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: IS_MOBILE_WEB ? 4 : 6,
  },
  donationModalSubtitle: {
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  donationModalContent: {
    padding: IS_MOBILE_WEB ? 20 : 28,
  },
  donationMessageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: IS_MOBILE_WEB ? 12 : 16,
    backgroundColor: colors.backgroundTertiary,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    padding: IS_MOBILE_WEB ? 16 : 20,
    marginBottom: IS_MOBILE_WEB ? 20 : 24,
    borderLeftWidth: 4,
    borderLeftColor: colors.info,
  },
  donationMessageText: {
    flex: 1,
    fontSize: IS_MOBILE_WEB ? 15 : 18,
    color: colors.textPrimary,
    lineHeight: IS_MOBILE_WEB ? 22 : 26,
    fontWeight: '600',
  },
  donationButtonsContainer: {
    flexDirection: 'row',
    gap: IS_MOBILE_WEB ? 10 : 16,
    marginBottom: IS_MOBILE_WEB ? 16 : 20,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  donationButton: {
    flex: 1,
    minWidth: IS_MOBILE_WEB ? 100 : 120,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
    paddingVertical: IS_MOBILE_WEB ? 14 : 18,
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 20,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  donationButtonWhatsApp: {
    backgroundColor: colors.success,
  },
  donationButtonBit: {
    backgroundColor: colors.info,
  },
  donationButtonPayBox: {
    backgroundColor: colors.primary,
  },
  donationButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: IS_MOBILE_WEB ? 14 : 18,
    letterSpacing: 0.3,
  },
  donationNoteText: {
    fontSize: IS_MOBILE_WEB ? 13 : 16,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: IS_MOBILE_WEB ? 18 : 24,
    fontWeight: '400',
    fontStyle: 'italic',
  },
  donationCtaButtonTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: IS_MOBILE_WEB ? 8 : 12,
    backgroundColor: colors.secondary,
    paddingVertical: IS_MOBILE_WEB ? 12 : 18,
    paddingHorizontal: IS_MOBILE_WEB ? 16 : 28,
    borderRadius: IS_MOBILE_WEB ? 12 : 16,
    minWidth: IS_MOBILE_WEB ? 140 : 200,
    marginBottom: IS_MOBILE_WEB ? 16 : 20,
    alignSelf: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  donationCtaButtonTextTop: {
    color: colors.white,
    fontWeight: '800',
    fontSize: IS_MOBILE_WEB ? 13 : 18,
    letterSpacing: 0.3,
  },
} as any);
