/**
 * Shared community statistics shape and defaults (used by statsService and mapping tests).
 */
export type CommunityStats = Record<string, number>;

export const DEFAULT_STATS: CommunityStats = {
  moneyDonations: 0,
  volunteerHours: 0,
  rides: 0,
  events: 0,
  activeMembers: 0,
  monthlyDonations: 0,
  monthlyGrowthPct: 0,
  activeCities: 0,
  totalUsers: 0,
  dailyActiveUsers: 0,
  weeklyActiveUsers: 0,
  newUsersThisWeek: 0,
  newUsersThisMonth: 0,
  totalOrganizations: 0,
  citiesWithUsers: 0,
  userEngagementRate: 0,
  totalDonations: 0,
  donationsThisWeek: 0,
  donationsThisMonth: 0,
  activeDonations: 0,
  completedDonations: 0,
  itemDonations: 0,
  serviceDonations: 0,
  totalMoneyDonated: 0,
  recurringDonationsAmount: 0,
  uniqueDonors: 0,
  siteVisits: 0,
  avgDonationAmount: 0,
  totalRides: 0,
  ridesThisWeek: 0,
  ridesThisMonth: 0,
  activeRides: 0,
  completedRides: 0,
  totalSeatsOffered: 0,
  uniqueDrivers: 0,
  avgSeatsPerRide: 0,
  totalEvents: 0,
  eventsThisWeek: 0,
  eventsThisMonth: 0,
  activeEvents: 0,
  completedEvents: 0,
  totalEventAttendees: 0,
  virtualEvents: 0,
  totalActivities: 0,
  activitiesToday: 0,
  activitiesThisWeek: 0,
  totalLogins: 0,
  donationActivities: 0,
  chatActivities: 0,
  activeUsersTracked: 0,
  totalMessages: 0,
  totalConversations: 0,
  messagesThisWeek: 0,
  groupConversations: 0,
  directConversations: 0,
  completedTasks: 0,
  foodKg: 0,
  clothingKg: 0,
  bloodLiters: 0,
  courses: 0,
  treesPlanted: 0,
  animalsAdopted: 0,
  recyclingBags: 0,
  culturalEvents: 0,
  appActiveUsers: 0,
  appDownloads: 0,
  activeVolunteers: 0,
  kmCarpooled: 0,
  fundsRaised: 0,
  mealsServed: 0,
  booksDonated: 0,
};
