import { StyleSheet } from 'react-native';
import colors from '../globals/colors';

export const createPostComposerModalStyles = StyleSheet.create({
  backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.35)' },
  backdropWeb: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: 2147483000,
  } as const,
  backdropTouch: { flex: 1 },
  sheet: { maxHeight: '85%', backgroundColor: colors.white, borderTopLeftRadius: 18, borderTopRightRadius: 18, padding: 16 },
  sheetTask: { height: '85%', maxHeight: '85%' },
  taskFormWrap: { flex: 1, minHeight: 200, marginBottom: 4 },
  sheetWeb: { zIndex: 2147483001 },
  handle: { alignSelf: 'center', width: 44, height: 5, borderRadius: 12, backgroundColor: colors.border, marginBottom: 8 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  title: { fontWeight: '700', color: colors.textPrimary, fontSize: 18 },
  toggleRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  toggleBtn: { flex: 1, borderRadius: 12, borderWidth: 1, borderColor: colors.border, paddingVertical: 10, alignItems: 'center' },
  toggleBtnActive: { backgroundColor: colors.successLight, borderColor: colors.success },
  requestBtnActive: { backgroundColor: colors.warningLight, borderColor: colors.warning },
  toggleText: { fontWeight: '600', color: colors.textPrimary },
  categoriesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  categoryChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 14, borderWidth: 1, borderColor: colors.border },
  categoryChipActive: { backgroundColor: colors.infoLight, borderColor: colors.primary },
  categoryText: { color: colors.textPrimary, fontSize: 12 },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: colors.textPrimary, marginBottom: 4, textAlign: 'right' },
  requiredStar: { color: colors.warning },
  input: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 10, color: colors.textPrimary },
  multiline: { minHeight: 80, textAlignVertical: 'top' },
  hintText: { color: colors.textSecondary, marginBottom: 12, textAlign: 'center' },
  advancedToggleFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 4,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  advancedToggleSide: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  advancedScroll: { maxHeight: 240, marginBottom: 4 },
  advancedToggleText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
    textAlign: 'center',
  },
  advancedPanel: { marginBottom: 8 },
  advancedBlock: { marginBottom: 12 },
  subLabel: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, marginBottom: 6, marginTop: 8, textAlign: 'right' },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
    marginEnd: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backgroundSecondary,
  },
  checkboxChecked: { backgroundColor: colors.primary, borderColor: colors.primary },
  checkboxLabel: { fontSize: 14, color: colors.textPrimary, flex: 1, textAlign: 'right' },
  freqRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  freqLabel: { fontSize: 13, color: colors.textPrimary },
  freqInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 56,
    textAlign: 'center',
    fontSize: 16,
    color: colors.textPrimary,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8, justifyContent: 'flex-end' },
  chipRowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10, justifyContent: 'flex-end' },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.backgroundSecondary,
  },
  chipActive: { borderColor: colors.primary, backgroundColor: colors.infoLight },
  chipText: { fontSize: 13, color: colors.textPrimary },
  chipTextActive: { fontWeight: '700', color: colors.primary },
  stepperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 16, marginBottom: 12 },
  stepperBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backgroundSecondary,
  },
  stepperBtnText: { fontSize: 22, fontWeight: '600', color: colors.textPrimary },
  stepperValue: { fontSize: 18, fontWeight: '700', minWidth: 32, textAlign: 'center', color: colors.textPrimary },
  submitBtn: { marginTop: 8, backgroundColor: colors.success, paddingVertical: 12, borderRadius: 12, alignItems: 'center', minHeight: 48, justifyContent: 'center' },
  submitRequest: { backgroundColor: colors.warning },
  submitBtnDisabled: { opacity: 0.45 },
  submitText: { color: colors.white, fontWeight: '700' },
});

export type CreatePostComposerModalStyles = typeof createPostComposerModalStyles;
