import { StyleSheet } from 'react-native';
import colors from '../globals/colors';

export const createPostComposerModalStyles = StyleSheet.create({
  backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' },
  backdropWeb: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: 2147483000,
  } as const,
  backdropTouch: { flex: 1 },
  sheet: {
    width: '100%',
    maxHeight: '90%',
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 24,
  },
  sheetTask: { height: '90%', maxHeight: '90%' },
  taskFormWrap: { flex: 1, minHeight: 200, marginBottom: 4 },
  sheetWeb: { 
    zIndex: 2147483001, 
    borderBottomLeftRadius: 32, 
    borderBottomRightRadius: 32, 
    alignSelf: 'center',
    width: '94%',
    maxWidth: 500,
    marginVertical: '5%',
  },
  handle: {
    alignSelf: 'center',
    width: 48,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.borderSecondary,
    marginBottom: 20,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'center', // Center title
    alignItems: 'center',
    marginBottom: 20,
    position: 'relative',
  },
  title: {
    fontWeight: '800',
    color: colors.textPrimary,
    fontSize: 22,
    textAlign: 'center',
  },
  closeButton: {
    position: 'absolute',
    right: 0,
    padding: 4,
  },
  closeButtonLeft: {
    position: 'absolute',
    left: 0,
    padding: 4,
  },
  toggleRow: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceGrayBlue,
    borderRadius: 16,
    padding: 4,
    marginBottom: 20,
  },
  toggleBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnActive: {
    backgroundColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  giveTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  requestTextActive: {
    color: colors.warning,
    fontWeight: '700',
  },
  toggleText: {
    fontWeight: '600',
    color: colors.textTertiary,
    fontSize: 15,
  },
  categoriesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
    justifyContent: 'center',
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.surfaceGrayBlue,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  categoryChipActive: {
    backgroundColor: colors.white,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  categoryText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  categoryTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 8,
    textAlign: 'right', // Default to RTL
  },
  fieldLabelLtr: {
    textAlign: 'left',
  },
  requiredStar: { color: colors.error },
  input: {
    backgroundColor: colors.surfaceGrayBlue,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
    color: colors.textPrimary,
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  inputFocused: {
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  multiline: { minHeight: 100, textAlignVertical: 'top' },
  hintText: { color: colors.textSecondary, marginBottom: 12, textAlign: 'center', fontSize: 14 },
  advancedToggleFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.borderSecondary,
  },
  advancedToggleSide: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  advancedScroll: { maxHeight: 280, marginBottom: 8 },
  advancedToggleText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
    textAlign: 'center',
  },
  advancedPanel: { marginBottom: 12 },
  advancedBlock: { marginBottom: 16 },
  subLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textSecondary,
    marginBottom: 10,
    marginTop: 12,
    textAlign: 'right',
  },
  subLabelLtr: {
    textAlign: 'left',
  },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.border,
    marginEnd: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  checkboxChecked: { backgroundColor: colors.primary, borderColor: colors.primary },
  checkboxLabel: { fontSize: 15, color: colors.textPrimary, flex: 1, textAlign: 'right', fontWeight: '500' },
  checkboxLabelLtr: { textAlign: 'left' },
  freqRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  freqLabel: { fontSize: 14, color: colors.textPrimary, fontWeight: '600' },
  freqInput: {
    backgroundColor: colors.surfaceGrayBlue,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 64,
    textAlign: 'center',
    fontSize: 16,
    color: colors.textPrimary,
    fontWeight: '700',
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 12, justifyContent: 'flex-end' },
  chipRowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 14, justifyContent: 'flex-end' },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: colors.surfaceGrayBlue,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  chipActive: { borderColor: colors.primary, backgroundColor: colors.white, shadowColor: colors.primary, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  chipText: { fontSize: 14, color: colors.textSecondary, fontWeight: '500' },
  chipTextActive: { fontWeight: '700', color: colors.primary },
  stepperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 20, marginBottom: 16 },
  stepperBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceGrayBlue,
  },
  stepperBtnText: { fontSize: 24, fontWeight: '600', color: colors.primary },
  stepperValue: { fontSize: 20, fontWeight: '800', minWidth: 40, textAlign: 'center', color: colors.textPrimary },
  submitBtn: {
    marginTop: 12,
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    minHeight: 56,
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  submitRequest: { backgroundColor: colors.warning, shadowColor: colors.warning },
  submitBtnDisabled: { opacity: 0.4, shadowOpacity: 0, elevation: 0 },
  submitText: { color: colors.white, fontWeight: '800', fontSize: 17, letterSpacing: 0.5 },
});

export type CreatePostComposerModalStyles = typeof createPostComposerModalStyles;
